# Default options for merging mobs.
#   Radius: how many blocks in each direction to search for entities to merge
#   Interval: How often, in seconds, to search for entities. Values less than 1 will be reverted to 1.
#   Count: The maximum number of entities to merge. -1 for infinite.
#   Color: The ChatColor to merged mobs names to for easier distinction.
#   Tag: The scoreboard tag to tag merged entities with.
default:
  radius: 5   # That radius to search around every entity.
  interval: 3 # How often, in seconds, to search for entities to merge.
  count: 65536 # The maximum number of entities that can be merged into a single 'merged entity'; -1 for infinite.
  color: red   # The default ChatColor of the merged entity's nametag.
  tag: mergedEntity # What scoreboard tag to tag this entity with. Currently not used.

# Which mobs to merge. This acts as a whitelist.
# Use Minecraft names for these, not the names Bukkit's EntityType assigns them.
# Default: Which mobs should always be merged.
#   - Placeholders:
#     - living -> for all living entities (cows, sheep, skeletons, etc.)
mobs:
  custom-name-visible: true # If the entity's custom name (after being merged should be visible)
  default:
    - living
  zombie:
    radius: [5, 3, 5]
# Which worlds to not merge mobs in.
# You can also use the UUID of a world.
excluded-worlds:
  - world_nether
# If this plugin should be verbose about all errors. Not just major ones.
# This could potentially spam your console. Please use caution when enabling this!
verbose: false
