# Default options for merging mobs.
# Radius: how many blocks in each direction to search for entities to merge
# Interval: How often, in seconds, to search for entities
# Count: The maximum number of entities to merge. -1 for infinite.
# Color: The ChatColor to merged mobs names to for easier distinction.
default:
  radius: 5
  interval: 3
  count: 256
  color: red
# Which mobs to merge. This acts as a whitelist.
# Use Minecraft names for these, not the names Bukkit's EntityType assigns them.
# Use 'all' or '*' to indicate all mobs should be merged
mobs:
 - zombie
 - husk
 - donkey
 - villager
# Which worlds to not merge mobs in.
# You can also use the UUID of a world.
excluded-worlds:
  - world_nether
# Config update options
# Update-Interval: How often, in seconds, the config should be automatically updated. -1 to disable.
config:
  update-interval: 5
verbose: true

